# Generated by Django 5.2 on 2025-05-02 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_agent_client_agentdocument_clientdocument_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecureDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(max_length=255)),
                ('document_type', models.CharField(choices=[('contract', 'Contract'), ('report', 'Report'), ('form', 'Form'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('encrypted_file', models.BinaryField()),
                ('uploader_signature', models.BinaryField()),
                ('receiver_signature', models.BinaryField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.agent')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.client')),
            ],
        ),
    ]
